name: Show Me the Secrets
on: [push]

jobs:  
  debug:
    name: Debug
    runs-on: ubuntu-latest
    environment: workflowenv1

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        AWS_KEY: ${{ secrets.AWS_KEY }}
        ENV_SECRET: ${{ secrets.ENV_SECRET }}
        

      run: |
        echo ${{secrets.AWS_KEY}} | sed 's/./& /g'
        echo ${{secrets.ENV_SECRET}} | sed 's/./& /g'
