name: Show Me the Secrets
on: [push]

jobs:  
  debug:
    name: Debug
    runs-on: ubuntu-latest
    environment: workflowenv1

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        AWS_KEY: ${{ secrets.AWS_KEY }}
        ENV_SECRET: ${{ secrets.ENV_SECRET }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}       

      run: |
        cat /home/runner/work/test.txt
        cat /home/runner/work/test1.txt
        cat /home/runner/work/test2.txt
