name: Build and Verify Code

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Checksum Before Build
        id: before-build
        run: |
          cd src/
          find . -type f -exec sha256sum {} \; > before_checksums.txt
        shell: bash

      - name: Build Code
        run: |
          # Your build commands here
        shell: bash

